name: 'Generate Dependabot Glob'

branding:
  icon: briefcase
  color: orange

description: 'Creates a `dependabot.yml` dynamically based on glob patterns.'
inputs:
  template-file:
    description: 'Location of the file to use as template'
    default: .github/dependabot.template.yml

  follow-symbolic-links:
    description: 'Indicates whether to follow symbolic links'
    default: true

runs:
  using: 'node16'
  main: 'dist/index.js'
